spring.application.name=competitioncubes
server.port=8030
wca.app.id=DvHxgmrdT6avSDdHstZrk00agtiO1ztYRo_ajPQDsKU
wca.app.secret=UJUxY_MzCo6wjsE3sE0jPlslHdtDfEVr4Abh2XUsABI
spring.datasource.url=jdbc:postgresql://localhost:5432/competition_cubes_main
spring.datasource.username=postgres
spring.datasource.password=Ph4nt0m37!!!
server.error.whitelabel.enabled=false
logging.level.com=INFO
kofi.verification.token=d7419418-e4dd-4c28-ab4b-47dc135229cf
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=Ph4nt0m37!!!
#server.ssl.key-alias=tomcat
#server.ssl.enabled=true

#Rate Limiting Stuff
# enable/disable bucket4j support
#false for now because its not working
bucket4j.enabled=false

#name of the limit
bucket4j.filters[0].cache-name=default
#url it applies to
bucket4j.filters[0].url=/.*
#number of tokens per time
bucket4j.filters[0].rate-limits[0].bandwidths[0].capacity=30
bucket4j.filters[0].rate-limits[0].bandwidths[0].time=1
bucket4j.filters[0].rate-limits[0].bandwidths[0].unit=minutes

# Default Properties which can be overiden for the filters
bucket4j.default-http-content-type=application/json
 # Enum value of org.springframework.http.HttpStatus
bucket4j.default-http-status-code=TOO_MANY_REQUESTS
  # the json response which should be added to the body
bucket4j.default-http-response-body={ "message": "Too many requests!" }
# Optional default metric tags for all filters
