spring.application.name=competitioncubes
server.port=8030
wca.app.id=DvHxgmrdT6avSDdHstZrk00agtiO1ztYRo_ajPQDsKU
wca.app.secret=UJUxY_MzCo6wjsE3sE0jPlslHdtDfEVr4Abh2XUsABI
postgres.url=jdbc:postgresql://localhost:5432/competitioncubestest
postgres.username=postgres
postgres.password=Ph4nt0m37!!!
server.ssl.key-store-type=PKCS12
server.ssl.key-store=classpath:keystore.p12
server.ssl.key-store-password=Ph4nt0m37!!!
server.ssl.key-alias=tomcat
server.ssl.enabled=true