spring.application.name=competitioncubes
server.port=8030
#server.ssl.key-store-type=PKCS12
#server.ssl.key-store=classpath:keystore.p12
#server.ssl.key-store-password=Ph4nt0m37!!!
#server.ssl.key-alias=tomcat
#server.ssl.enabled=true